<a href="https://colab.research.google.com/github/benjiPro-Bayou/Machine-Learning/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [3]:
y = torch.tensor([
    [1,2,3],
    [2,3,4],
    [0,0,0]], dtype= torch.float)
y

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [0., 0., 0.]])

In [4]:
torch.ones(1,2, dtype=torch.int)

tensor([[1, 1]], dtype=torch.int32)

In [5]:
torch.zeros(5,3,2, dtype=torch.float)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [6]:
z= torch.rand(3,4,2, dtype= torch.float)
z

tensor([[[0.6866, 0.0612],
         [0.4227, 0.3340],
         [0.7815, 0.4726],
         [0.1628, 0.7876]],

        [[0.1596, 0.0974],
         [0.9134, 0.2055],
         [0.7863, 0.8911],
         [0.5368, 0.9949]],

        [[0.6127, 0.4144],
         [0.8496, 0.4696],
         [0.1544, 0.0323],
         [0.7758, 0.1408]]])

In [7]:
print(y)
y[0]

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [0., 0., 0.]])


tensor([1., 2., 3.])

In [8]:
y[:,1]

tensor([2., 3., 0.])

In [9]:
z[2,:,0]

tensor([0.6127, 0.8496, 0.1544, 0.7758])